### ISSUE TITLE
Isotope definition

### ISSUE THREAD

**Issue by bplimley** [bearing/radwatch-analysis#4]
Define an object that represents the physical properties of one gamma-emitting radioisotope.

Include attributes:
1. Atomic number
2. Mass number
3. Symbol
4. Half life in seconds
5. Decay constant in seconds
6. List of significant gamma emission energies
7. List of significant gamma emission branching ratios

It would probably be worthwhile to try scraping this info from the online TOI (http://nucleardata.nuclear.lu.se/toi/)

**Comment by Canonicus777** [comment]
Resolved with pull request #7 of Gamma_Analysis.
