### ISSUE TITLE
Zeros in output CSVs

### ISSUE THREAD

**Issue by bplimley** [bearing/radwatch-analysis#45]
The output files `Sampling_Table.csv` and `Website_Table.csv` contain mainly `0.0` for Cs-137 and Cs-134 activities as well as uncertainties.

This may be a rounding issue, or something else.

Apparently Chris had a version of code that worked properly, and sent a copy to @tybtab a couple weeks ago. That may be helpful in determining the problem, but of course `bearing/master` has a lot of updates recently that we don't want to regress.

**Comment by tybtab** [comment]
This is addressed in #50 pull request
