### ISSUE TITLE
Test analysis script

### ISSUE THREAD

**Issue by bplimley** [bearing/radwatch-analysis#6]
- Add an SPE file of a past measurement
- In a new file, write a script that imports your other code, loads the SPE and measures the concentration of K-40, Cs-137, and others in Bq. This should basically use all of the code you've written so far, except maybe the web scraping.
- If any steps in this test analysis script are awkward or require additional handling of data, that means that we will want to add to or revise the gamma analysis code.

**Comment by Canonicus777** [comment]
Resolved with pull request #7 of Gamma_Analysis.
